sudo: required

language: node_js

node_js:
  - "4.1"

services:
  - docker

before install:
  - docker-compose --no-cache
  - docker-compose up -d
  - sleep 3
  - docker ps -a

scripts:
  - cd tests
  - docker ps -a
  - mocha 