sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.1"

before_install:
  - docker-compose --no-cache
  - docker-compose up -d
  - sleep 3
  - docker ps -a

install: true

scripts:
  - cd tests
  - docker ps -a
  - mocha 